### ISSUE TITLE
Improve site SEO

### ISSUE THREAD

**Issue by banta** [nairuby/arc_platform#59]
The following should be prioritized

1. Dynamic meta tags for all pages - title, description
2. robots.txt file
3. Dynamic sitemap
4. alt for all images

**Comment by Harrisonkamau** [comment]
Hello @banta!

This is a pretty good issue. Do we have a Google Search Console account that could be used to submit the sitemap? We could use it to test the `robots.txt` file.

We could use [sitemap_generator](https://rubygems.org/gems/sitemap_generator) to set up a dynamic sitemap.

Below are my follow-up questions:
1. What endpoints do we want to protect from crawling by search engines?
2. Also, since `robots.txt` is not a foolproof technical for keeping pages out of search engines, would we want to consider protecting sensitive information in other ways such as authorization and such?

**Comment by AJ-Kulundu** [comment]
@JudahSan  You can review the open pull request #69 and send me feedback.

**Comment by JudahSan** [comment]
@AJ-Kulundu, Please focus on addressing the following unresolved issues:

- [x] Document does not have a meta description
- [ ] Links do not have descriptive test
- [ ] Image elements do not have [alt] attribute

Thank you!

![image](https://github.com/nairuby/arc_platform/assets/61739631/9ae67404-8e48-4444-b32e-e92a1caa94b1)

![image](https://github.com/nairuby/arc_platform/assets/61739631/6f47955b-dcd0-4bb3-98a5-cd0f3c27eb45)

**Comment by AJ-Kulundu** [comment]
@JudahSan PR #77 should have the necessary changes
